services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitamines_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./backup:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - backend

  api:
    build: ./vitaminesApi
    container_name: vitamines-api
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=vitamines_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3000:3000"
    networks:
      - backend

  frontend:
    build: ./vitamines
    container_name: vitamines-frontend
    depends_on:
      - api
    ports:
      - "5173:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
